### PR TITLE
update Puppetfile.lock for 1.16 RC2

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
If wanted, we could also update some dependencies...

**Comment by ekohl** [comment]
> If wanted, we could also update some dependencies...

Let's do that.

**Comment by mmoll** [comment]
updated some dependencies.

**Review by ekohl — APPROVED** [review]
This does mean we need similar katello changes to allow extlib 3 but I'll fix that.

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
