### PR TITLE
Refs #22513 - use appropriate puppetlabs/postgresql release

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Review by mmoll — CHANGES_REQUESTED** [review]
Puppetfile.lock also needs to get updated.

**Comment by ekohl** [comment]
Updated. Also added a commit to bump 2 other dependencies while we're still in RC phase.

**Comment by mmoll** [comment]
Allright, let's wait for the next BATS test of nightlies with that update applied and then merge it for 1.18.

**Comment by ekohl** [comment]
@mmoll the latest nightly with bats passed. Any other objections?

**Review by mmoll — APPROVED** [review]

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
