### PR TITLE
Add webhooks CLI plugin

### PR DESCRIPTION
**Pull request by ofedoren**
Related to https://github.com/theforeman/puppet-foreman/pull/977.

Also needs to be CPed into 2.5.

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Coudld you have matching timestamps for the migrations? https://github.com/theforeman/foreman-installer/blob/develop/bin/create-migration is a helper that makes it easy. You can even input the migration on STDIN.

**Comment by ofedoren** [comment]
@ekohl, I've created those migrations via this exact script, I guess I didn't notice that multiple directories can be used... Thanks, updated.

**Comment by ehelms** [comment]
[test foreman-installer]

**Comment by ofedoren** [comment]
[test foreman-installer]

**Comment by ekohl** [comment]
I think you may need to rebase now.

**Comment by ofedoren** [comment]
Thanks, done.

**Comment by ofedoren** [comment]
@ekohl should I open a CP PR?

**Comment by ekohl** [comment]
We'll need a cherry pick of puppet-foreman as well for that. It would have been easier to have a Redmine issue for that so we wouldn't lose track of it.

**Pull request merged**
