### PR TITLE
Add create_resources from puppetlabs to make this work on 2.6

### PR DESCRIPTION
**Pull request by GregSutcliffe**
New PR to merge this to develop instead of master

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Will rebase this in a sec

**Comment by GregSutcliffe** [comment]
@skottler this is mergable now, can you test on EPEL? I'll do debian in a moment, when I fix my server here...

**Comment by skottler** [comment]
Works flawlessly on Puppet 2.6.17.

**Comment by skottler** [comment]
Merged - thanks!

**Comment by GregSutcliffe** [comment]
For posterity - Works on debian 2.6.14. Obviously fails on debian-stable stock 2.6.2 due to a lack of param-class support.

**Pull request closed without merging**
