### PR TITLE
Fixes #32659 - Support Puppet 7

### PR DESCRIPTION
**Pull request by ekohl**
This is currently a draft, but it runs the tests to give a list of modules that need attention.

### CODE REVIEW

**Comment by ekohl** [comment]
[test foreman-installer]

**Comment by ekohl** [comment]
[test foreman-installer]

**Comment by ekohl** [comment]
[test foreman-installer]

**Comment by ekohl** [comment]
[test foreman-installer]

**Comment by ehelms** [comment]
[test foreman-installer]

**Comment by ehelms** [comment]
Bummer, testing is still blocked on our dependent modules, current blocker https://github.com/puppetlabs/puppetlabs-xinetd/pull/121

**Comment by ekohl** [comment]
This is finally green! I'm manually testing a Puppet 6 -> 7 migration to test my hook.

**Comment by ekohl** [comment]
Looks like it works as I intended:

```console
# dnf remove -y puppet6-release
...
# dnf install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
...
# dnf update -y
...
# foreman-installer -l info
2021-07-28 16:13:02 [INFO  ] [pre_migrations] Executing hooks in group pre_migrations
2021-07-28 16:13:02 [INFO  ] [pre_migrations] All hooks in group pre_migrations finished
2021-07-28 16:13:02 [INFO  ] [boot] Executing hooks in group boot
2021-07-28 16:13:02 [INFO  ] [boot] All hooks in group boot finished
2021-07-28 16:13:02 [NOTICE] [root] Loading installer configuration. This will take some time.
2021-07-28 16:13:02 [INFO  ] [init] Executing hooks in group init
2021-07-28 16:13:02 [INFO  ] [init] All hooks in group init finished
2021-07-28 16:13:02 [INFO  ] [root] Loading default values from puppet modules...
2021-07-28 16:13:07 [INFO  ] [root] ... finished loading default values from puppet modules.
2021-07-28 16:13:07 [INFO  ] [pre_values] Executing hooks in group pre_values
2021-07-28 16:13:07 [INFO  ] [pre_values] All hooks in group pre_values finished
2021-07-28 16:13:08 [NOTICE] [root] Running installer with log based terminal output at level INFO.
2021-07-28 16:13:08 [NOTICE] [root] Use -l to set the terminal output log level to ERROR, WARN, NOTICE, INFO, or DEBUG. See --full-help for definitions.
2021-07-28 16:13:09 [INFO  ] [pre_validations] Executing hooks in group pre_validations
2021-07-28 16:13:11 [INFO  ] [pre_validations] All hooks in group pre_validations finished
2021-07-28 16:13:11 [INFO  ] [root] Running validation checks.
2021-07-28 16:13:11 [INFO  ] [pre_commit] Executing hooks in group pre_commit
2021-07-28 16:13:11 [INFO  ] [pre_commit] All hooks in group pre_commit finished
2021-07-28 16:13:11 [INFO  ] [pre] Executing hooks in group pre
2021-07-28 16:13:16 [INFO  ] [pre] Ensuring foreman-selinux to package state installed
2021-07-28 16:13:20 [INFO  ] [pre] All hooks in group pre finished
2021-07-28 16:13:20 [NOTICE] [configure] Starting system configuration.
2021-07-28 16:13:29 [INFO  ] [configure] Compiled catalog for centos8-foreman-nightly.wisse.example.com in environment production in 3.73 seconds
2021-07-28 16:13:32 [NOTICE] [configure] 250 configuration steps out of 1350 steps complete.
2021-07-28 16:13:33 [INFO  ] [configure] /Stage[main]/Puppet::Server::Puppetserver/File[/etc/puppetlabs/puppetserver/conf.d/puppetserver.conf]/content:
2021-07-28 16:13:33 [INFO  ] [configure] --- /etc/puppetlabs/puppetserver/conf.d/puppetserver.conf	2021-07-28 16:01:54.272361133 +0000
2021-07-28 16:13:33 [INFO  ] [configure] +++ /tmp/puppet-file20210728-3512-g3fjxq	2021-07-28 16:13:33.036987677 +0000
2021-07-28 16:13:33 [INFO  ] [configure] @@ -61,12 +61,6 @@
2021-07-28 16:13:33 [INFO  ] [configure] # (optional) Sets the upper limit for the random sleep set as a Retry-After header on 503 responses returned when max-queued-requests is enabled.
2021-07-28 16:13:33 [INFO  ] [configure] max-retry-delay: 1800
2021-07-28 16:13:33 [INFO  ] [configure] 
2021-07-28 16:13:33 [INFO  ] [configure] -    # (optional) Authorize access to Puppet master endpoints via rules
2021-07-28 16:13:33 [INFO  ] [configure] -    # specified in the legacy Puppet auth.conf file (if true) or via rules
2021-07-28 16:13:33 [INFO  ] [configure] -    # specified in the Puppet Server HOCON-formatted auth.conf (if false or not
2021-07-28 16:13:33 [INFO  ] [configure] -    # specified).
2021-07-28 16:13:33 [INFO  ] [configure] -    use-legacy-auth-conf: false
2021-07-28 16:13:33 [INFO  ] [configure] -
2021-07-28 16:13:33 [INFO  ] [configure] # (optional) enable or disable environment class cache
2021-07-28 16:13:33 [INFO  ] [configure] environment-class-cache-enabled: false
2021-07-28 16:13:33 [INFO  ] [configure] multithreaded: false
2021-07-28 16:13:33 [INFO  ] [configure] /Stage[main]/Puppet::Server::Puppetserver/File[/etc/puppetlabs/puppetserver/conf.d/puppetserver.conf]/content: content changed '{sha256}325512417d304fe39c19c9d3bdc706404edfd0606ed0c70007716d281ef4bbc8' to '{sha256}75e845319f541454e99b27e07a7f697354bdc89698a177d035ff090c6305afd6'
2021-07-28 16:13:33 [INFO  ] [configure] /Stage[main]/Puppet::Server::Puppetserver/File[/etc/puppetlabs/puppetserver/conf.d/webserver.conf]/content:
2021-07-28 16:13:33 [INFO  ] [configure] --- /etc/puppetlabs/puppetserver/conf.d/webserver.conf	2021-07-20 12:29:11.340387705 +0000
2021-07-28 16:13:33 [INFO  ] [configure] +++ /tmp/puppet-file20210728-3512-dxxdgx	2021-07-28 16:13:33.072988296 +0000
2021-07-28 16:13:33 [INFO  ] [configure] @@ -8,9 +8,9 @@
2021-07-28 16:13:33 [INFO  ] [configure] ssl-port: 8140
2021-07-28 16:13:33 [INFO  ] [configure] ssl-cert: /etc/puppetlabs/puppet/ssl/certs/centos8-foreman-nightly.wisse.example.com.pem
2021-07-28 16:13:33 [INFO  ] [configure] ssl-key: /etc/puppetlabs/puppet/ssl/private_keys/centos8-foreman-nightly.wisse.example.com.pem
2021-07-28 16:13:33 [INFO  ] [configure] -    ssl-ca-cert: /etc/puppetlabs/puppet/ssl/ca/ca_crt.pem
2021-07-28 16:13:33 [INFO  ] [configure] -    ssl-crl-path: /etc/puppetlabs/puppet/ssl/ca/ca_crl.pem
2021-07-28 16:13:33 [INFO  ] [configure] -    ssl-cert-chain: /etc/puppetlabs/puppet/ssl/ca/ca_crt.pem
2021-07-28 16:13:33 [INFO  ] [configure] +    ssl-ca-cert: /etc/puppetlabs/puppetserver/ca/ca_crt.pem
2021-07-28 16:13:33 [INFO  ] [configure] +    ssl-crl-path: /etc/puppetlabs/puppetserver/ca/ca_crl.pem
2021-07-28 16:13:33 [INFO  ] [configure] +    ssl-cert-chain: /etc/puppetlabs/puppetserver/ca/ca_crt.pem
2021-07-28 16:13:33 [INFO  ] [configure] idle-timeout-milliseconds: 30000
2021-07-28 16:13:33 [INFO  ] [configure] ssl-protocols: [
2021-07-28 16:13:33 [INFO  ] [configure] TLSv1.2,
2021-07-28 16:13:33 [INFO  ] [configure] /Stage[main]/Puppet::Server::Puppetserver/File[/etc/puppetlabs/puppetserver/conf.d/webserver.conf]/content: content changed '{sha256}3974993721961d55c17ab7e4e17c7be78d7c35f68e2b65b7cd978a5e38984866' to '{sha256}554e09541e4aa5d0d5f6964b9628c85322898994e63a0f6e6ba15a0a615f09de'
2021-07-28 16:13:33 [INFO  ] [configure] /Stage[main]/Puppet::Server::Config/Exec[migrate Puppetserver cadir]/returns: executed successfully
2021-07-28 16:13:33 [INFO  ] [configure] /Stage[main]/Puppet::Server::Config/File[/etc/puppetlabs/code/environments]/owner: owner changed 'root' to 'puppet'
2021-07-28 16:13:33 [INFO  ] [configure] /Stage[main]/Puppet::Server::Config/File[/etc/puppetlabs/code/modules]/owner: owner changed 'root' to 'puppet'
2021-07-28 16:13:33 [INFO  ] [configure] /Stage[main]/Puppet::Server::Config/File[/opt/puppetlabs/puppet/modules]/owner: owner changed 'root' to 'puppet'
2021-07-28 16:13:33 [INFO  ] [configure] /Stage[main]/Puppetserver_foreman/File[/etc/puppetlabs/puppet/foreman.yaml]/content:
2021-07-28 16:13:33 [INFO  ] [configure] --- /etc/puppetlabs/puppet/foreman.yaml	2021-07-20 12:29:11.438389502 +0000
2021-07-28 16:13:33 [INFO  ] [configure] +++ /tmp/puppet-file20210728-3512-gj9ba8	2021-07-28 16:13:33.459994948 +0000
2021-07-28 16:13:33 [INFO  ] [configure] @@ -1,12 +1,12 @@
2021-07-28 16:13:33 [INFO  ] [configure] ---
2021-07-28 16:13:33 [INFO  ] [configure] :url: "https://centos8-foreman-nightly.wisse.example.com"
2021-07-28 16:13:33 [INFO  ] [configure] -:ssl_ca: "/etc/puppetlabs/puppet/ssl/ca/ca_crt.pem"
2021-07-28 16:13:33 [INFO  ] [configure] +:ssl_ca: "/etc/puppetlabs/puppetserver/ca/ca_crt.pem"
2021-07-28 16:13:33 [INFO  ] [configure] :ssl_cert: "/etc/puppetlabs/puppet/ssl/certs/centos8-foreman-nightly.wisse.example.com.pem"
2021-07-28 16:13:33 [INFO  ] [configure] :ssl_key: "/etc/puppetlabs/puppet/ssl/private_keys/centos8-foreman-nightly.wisse.example.com.pem"
2021-07-28 16:13:33 [INFO  ] [configure] :puppetdir: "/opt/puppetlabs/server/data/puppetserver"
2021-07-28 16:13:33 [INFO  ] [configure] :puppetuser: "puppet"
2021-07-28 16:13:33 [INFO  ] [configure] :facts: true
2021-07-28 16:13:33 [INFO  ] [configure] -:fact_extension: "yaml"
2021-07-28 16:13:33 [INFO  ] [configure] +:fact_extension: "json"
2021-07-28 16:13:33 [INFO  ] [configure] :timeout: 60
2021-07-28 16:13:33 [INFO  ] [configure] :report_timeout: 60
2021-07-28 16:13:33 [INFO  ] [configure] :threads: null
2021-07-28 16:13:33 [INFO  ] [configure] /Stage[main]/Puppetserver_foreman/File[/etc/puppetlabs/puppet/foreman.yaml]/content: content changed '{sha256}01266aa8e582bc8878a1e2238b0c5f54570601c48cb78431bab70d8460493d48' to '{sha256}d5b633eea95436dc21b505cc7bff2f4701cb41440796d70a82f64add51b288f3'
2021-07-28 16:13:33 [NOTICE] [configure] 500 configuration steps out of 1352 steps complete.
2021-07-28 16:13:49 [NOTICE] [configure] 1000 configuration steps out of 1359 steps complete.
2021-07-28 16:14:14 [INFO  ] [configure] /Stage[main]/Puppet::Server::Service/Service[puppetserver]/ensure: ensure changed 'stopped' to 'running'
2021-07-28 16:14:14 [NOTICE] [configure] 1250 configuration steps out of 1359 steps complete.
2021-07-28 16:14:15 [INFO  ] [configure] /Stage[main]/Foreman_proxy::Module::Puppetca/Foreman_proxy::Module[puppetca]/Foreman_proxy::Settings_file[puppetca]/File[/etc/foreman-proxy/settings.d/puppetca.yml]/content:
2021-07-28 16:14:15 [INFO  ] [configure] --- /etc/foreman-proxy/settings.d/puppetca.yml	2021-07-28 16:02:32.455031694 +0000
2021-07-28 16:14:15 [INFO  ] [configure] +++ /tmp/puppet-file20210728-3512-1m7nqx6	2021-07-28 16:14:14.990708795 +0000
2021-07-28 16:14:15 [INFO  ] [configure] @@ -9,4 +9,4 @@
2021-07-28 16:14:15 [INFO  ] [configure] :use_provider: puppetca_hostname_whitelisting
2021-07-28 16:14:15 [INFO  ] [configure] 
2021-07-28 16:14:15 [INFO  ] [configure] # Puppet version used
2021-07-28 16:14:15 [INFO  ] [configure] -:puppet_version: 6.24.0
2021-07-28 16:14:15 [INFO  ] [configure] +:puppet_version: 7.9.0
2021-07-28 16:14:15 [INFO  ] [configure] /Stage[main]/Foreman_proxy::Module::Puppetca/Foreman_proxy::Module[puppetca]/Foreman_proxy::Settings_file[puppetca]/File[/etc/foreman-proxy/settings.d/puppetca.yml]/content: content changed '{sha256}672eae8e92a5d25dbecf39b3bd9086aeb0c577fbc0f14a4a8e20b225c74b64bc' to '{sha256}170b92f8080f82103f790fd8110e5b1a461d1a49e8c0d12803977ba35f717885'
2021-07-28 16:14:16 [INFO  ] [configure] /Service[foreman-proxy]: Triggered 'refresh' from 1 event
2021-07-28 16:14:17 [INFO  ] [configure] /Stage[main]/Foreman_proxy::Register/Foreman_smartproxy[centos8-foreman-nightly.wisse.example.com]: Triggered 'refresh' from 1 event
2021-07-28 16:14:17 [INFO  ] [configure] Applied catalog in 46.99 seconds
2021-07-28 16:14:20 [NOTICE] [configure] System configuration has finished.
2021-07-28 16:14:20 [INFO  ] [post] Executing hooks in group post
Executing: foreman-rake upgrade:run
API controllers newer than Apipie cache! Run apipie:cache rake task to regenerate cache.
  Success!
  * Foreman is running at https://centos8-foreman-nightly.wisse.example.com
  * Foreman Proxy is running at https://centos8-foreman-nightly.wisse.example.com:8443

  The full log is at /var/log/foreman-installer/foreman.log
2021-07-28 16:14:28 [INFO  ] [post] All hooks in group post finished
# ls -ld /etc/puppetlabs/puppet/ssl/ca /etc/puppetlabs/puppetserver/ca
drwxr-x---. 4 puppet puppet 232 Jul 20 12:33 /etc/puppetlabs/puppetserver/ca
lrwxrwxrwx. 1 puppet puppet  31 Jul 28 16:13 /etc/puppetlabs/puppet/ssl/ca -> /etc/puppetlabs/puppetserver/ca
```

Let's merge this :)

**Review by ehelms — APPROVED** [review]

**Comment by ekohl** [comment]
On my test machine I do see https://projects.theforeman.org/issues/33190 but I'd rather get this in now. I already had some issues on my test machine with imports. I'm merging this now since I confirmed it didn't regress Puppet 6. If anything, we can mark Puppet 7 as experimental.

**Pull request merged**
