### PR TITLE
Add a script to create migrations

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]
Have not tested it, but looks pretty straightforward.

**Comment by ekohl** [comment]
I should note that it's based on https://github.com/Katello/katello-installer/blob/master/bin/create-migration but I went with shell to keep it straight forward.

**Comment by ehelms** [comment]
I find this less straight forward. Bash is never as clean looking as Ruby, especially when I compare the two. Is there anyway we can move the foreman migrations to the same format easily so there is just one way to do things?

**Comment by ekohl** [comment]
I considered that, but we'll need to ensure we don't run migrations twice. I'll have a look what's possible

**Comment by ares** [comment]
I'd also prefer ruby implementation, but :+1: on the direction!

**Comment by ekohl** [comment]
Rewritten as Ruby now

**Review by ehelms — APPROVED** [review]

**Pull request merged**
