### PR TITLE
move migrate_cdn_setting to hooks/

### PR DESCRIPTION
**Pull request by wbclark**

### CODE REVIEW

**Comment by ehelms** [comment]
There is a pre hook component associated with this hook as well.

**Comment by ehelms** [comment]
@wbclark did you find out form @chris1984 or @jlsherrill if this is a hook we still need?

**Comment by chris1984** [comment]
I think we still need it since this was a migration from an installer parameter to one in the UI and we call a rake command to update that in the DB.

**Comment by chris1984** [comment]
I think @ekohl said it was safe to drop it at some point down the road but not sure when we should make that call?

**Comment by ehelms** [comment]
In what version of Katello was this change made? @chris1984

**Comment by chris1984** [comment]
@ehelms looks like 3.16.0 https://projects.theforeman.org/issues/28476

**Comment by wbclark** [comment]
Updated the move the pre_commit hook as well

**Review by ehelms — APPROVED** [review]

**Pull request merged**
