### PR TITLE
Fixes #31490 - Remove digital ocean plugin

### PR DESCRIPTION
**Pull request by snecklifter**
This plugin has not been maintained for a while now and causes
issues on installation. This commit removes the option from the
installer and can be easily reverted if the plugin is updated.

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
This needs a migration to also drop it from existing installations. In the bin directory there's a helper script to create the right files.

@timogoebel can you confirm that the plugin should be removed?

**Comment by timogoebel** [comment]
> @timogoebel can you confirm that the plugin should be removed?

Yeah, I'm afraid it makes sense to remove it from the installer.

**Comment by ekohl** [comment]
ok to test

**Review by ekohl — CHANGES_REQUESTED** [review]
I think this would also be good to capture in a Redmine issue for the changelog. Other than that, it looks good, let's see what the tests say.

**Comment by snecklifter** [comment]
> I think this would also be good to capture in a Redmine issue for the changelog. Other than that, it looks good, let's see what the tests say.

https://projects.theforeman.org/issues/31490

Please let me know if you need anything else.

**Comment by ekohl** [comment]
If you use `Fixes #31490 - Remove ...` as the first line in the commit message then it will automatically be linked and closed. This allows our automation to work.

**Review by ekohl — APPROVED** [review]
Thanks!

**Pull request merged**
