### PR TITLE
adding ovirt_provision plugin to installer options

### PR DESCRIPTION
**Pull request by bronhaim**
Signed-off-by: Yaniv Bronhaim ybronhei@redhat.com

### CODE REVIEW

**Comment by ekohl** [comment]
I assume this replaces https://github.com/theforeman/foreman-installer/pull/130. You can see that there's no need to close the PR and open a new one. Github will detect a force push (as you've done).

:+1: pending https://github.com/theforeman/puppet-foreman/pull/246

**Comment by bronhaim** [comment]
Yes, my bad. continue with that request please.

**Comment by domcleal** [comment]
You need to add an entry to answers.yaml too, else the installer doesn't recognise the argument.  Otherwise works fine.

**Comment by bronhaim** [comment]
Thanks. updated

**Comment by domcleal** [comment]
Merged as 9eff5bf, thanks @bronhaim.

**Pull request closed without merging**
