### PR TITLE
Installer configuration for remote execution

### PR DESCRIPTION
**Pull request by stbenjam**
Requires https://github.com/theforeman/puppet-foreman/pull/349 and https://github.com/theforeman/puppet-foreman_proxy/pull/187

### CODE REVIEW

**Comment by iNecas** [comment]
I've tested all the PRs together, and all worked well except the UI requiring sass for the scss. But nothing to be changed from this PRs point of view. ACK

**Comment by stbenjam** [comment]
@iNecas Thanks for testing it!

**Comment by stbenjam** [comment]
Installer puppet module PR's were merged.

**Comment by stbenjam** [comment]
Oh just kidding, the proxy's not done.

**Comment by domcleal** [comment]
Merged as 5f4055b, thanks @stbenjam.  I'll cherry pick to 1.10-stable too, as it'll be in the corresponding installer modules.

**Pull request closed without merging**
