### PR TITLE
Submodule bump and updates to puppet::server

### PR DESCRIPTION
**Pull request by GregSutcliffe**
Not bumped external submodules, these have new commits and should probably get tested:
- modified:   concat (new commits)
- modified:   mysql (new commits)
- modified:   postgresql (new commits)
- modified:   stdlib (new commits)
- modified:   xinetd (new commits)

### CODE REVIEW

**Comment by domcleal** [comment]
The server parameter of 'puppet' should be added as an option in generate_answers.

**Comment by GregSutcliffe** [comment]
Good catch, added.

**Comment by domcleal** [comment]
:+1: reads OK

**Comment by ekohl** [comment]
:+1: Assuming you've tested it.

**Comment by GregSutcliffe** [comment]
I tested generate_answers, I'll give it a full run through after lunch.

**Comment by GregSutcliffe** [comment]
Tested, merged. Thanks guys!

**Pull request merged**
