### PR TITLE
Switch puppetlabs/mysql back to a release

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by mmoll** [comment]
I'm unsure If the jump 3 -> 4 should be done in the 1.16 release cycle. While seeing that the major bump was only for Puppet version compatibility reasons, is there any gain form it?

**Comment by ekohl** [comment]
Given we only just released the RC I think this should still be safe and I'd prefer to be on a release for our releases.

**Comment by mmoll** [comment]
OK, please update Puppetfile.lock then :)

**Comment by mmoll** [comment]
this also updates theforeman-puppet abnd puppetlabs-apache, but that's OK 👍

**Comment by ekohl** [comment]
I know and I think those are actually good things

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
