### PR TITLE
setting minimal version of foreman_api to 0.1.4

### PR DESCRIPTION
**Pull request by lzap**
We need this patch

https://github.com/mbacovsky/foreman_api/commit/434e90f7f7a962cca8a284a196fa1e03b8d03d34

otherwise some requests (POST) will fail during oauth.

### CODE REVIEW

**Comment by domcleal** [comment]
This will break Fedora builds, as the latest version there is 0.1.3.

**Comment by lzap** [comment]
Right, asked @mbacovsky to do the builds for us.

Thanks!

LZ

On Tue, Jul 30, 2013 at 03:41:01AM -0700, Dominic Cleal wrote:

> This will break Fedora builds, as the latest version there is 0.1.3.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/theforeman/foreman-installer/pull/57#issuecomment-21782659

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by mbacovsky** [comment]
here are links to couple of recent builds in foreman-nightly. 
v 0.1.5-2
- [F-19](http://koji.katello.org/koji/buildinfo?buildID=5411)
- [F-18](http://koji.katello.org/koji/buildinfo?buildID=5410)
- [RHEL6](http://koji.katello.org/koji/buildinfo?buildID=5409)
- [RHEL6 SCL](http://koji.katello.org/koji/buildinfo?buildID=5408)

**Comment by domcleal** [comment]
Nice, thanks @mbacovsky.

@lzap could you update Fedora comps in foreman-packaging please so we publish foreman_api to those repos?  No PR necessary, just push.  Once that's done and it's in all our nightly repos, I'll merge this.

**Comment by domcleal** [comment]
@lzap never mind, it's already in there and in today's repos.

Merged as 078c993, thanks!

**Comment by lzap** [comment]
Oh sorry I did not get to that yet. Looks like it is already there :-) Thanks!

**Pull request closed without merging**
