### PR TITLE
Update katello/candlepin to 11.2.0 for pki-core

### PR DESCRIPTION
**Pull request by ekohl**
katello/candlepin 11.2.0 manages the installation of the pki-core module on EL8. It also drops the dependency on puppet/selinux which slightly trims down the installer.

It does raise the minimum Puppet version to 5.5.20+ or 6.15.0+ on EL8.

Blocked on https://github.com/theforeman/puppet-candlepin/pull/176

### CODE REVIEW

**Comment by ekohl** [comment]
[test foreman-installer]

**Comment by ekohl** [comment]
This should probably be combined with https://github.com/theforeman/foreman-installer/pull/653. While the pki-core fix in the module is not really needed, dropping the selinux module dependency is nice since it trims down the installer.

**Comment by ehelms** [comment]
I merged https://github.com/theforeman/foreman-installer/pull/653 -- please add it to this PR.

**Comment by ekohl** [comment]
Updated

**Review by ehelms — APPROVED** [review]

**Pull request merged**
