### PR TITLE
Fixes #30569 - Add migration to change logging pattern

### PR DESCRIPTION
**Pull request by tbrisker**
(cherry picked from commit 832e1fe70d2400b291ea829c1d0f09ad6641ab61)

### CODE REVIEW

**Comment by ekohl** [comment]
The change was only introduced in 16.0.0 but 2.2 includes 15.1.1.

**Comment by tbrisker** [comment]
The new layout and the error page pointing to the rake task that leverages it are in 2.2 core, and i've already seen a few reports on discourse using it which needed to be replied to asking the user to change their layout manually to get the actual stacktrace. can we pick https://github.com/theforeman/puppet-foreman/pull/847 to 15.1?

**Comment by ekohl** [comment]
@wbclark since you're on release rotation this week, mind taking this one?
@tbrisker https://github.com/theforeman/foreman/pull/8126 is IMHO also a good one to introduce.

**Comment by tbrisker** [comment]
opened https://github.com/theforeman/puppet-foreman/pull/902 for the changes needed in puppet-foreman for this (as well as another small change i noticed was missing and probably needed)

**Comment by tbrisker** [comment]
this will fail until 15.1.2 is released with the needed changes

**Comment by tbrisker** [comment]
[test foreman-installer]

**Pull request merged**
