### PR TITLE
Bump modules for 1.2.0

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ekohl** [comment]
Did you also bump xinetd to the latest?

**Comment by domcleal** [comment]
@ekohl I forgot that, thanks.  I'd been avoiding updating the external modules in case they broke things, but have now done so.

**Comment by GregSutcliffe** [comment]
SHAs check out :+1:

**Comment by ekohl** [comment]
Haven't tested, but :+1: to bumping.

**Pull request merged**
