### PR TITLE
Fixes #29243: Create new install file

### PR DESCRIPTION
**Pull request by ehelms**
Fixes regression where new install messages are being printed
all the time rather than only on new installs.

### CODE REVIEW

**Comment by ekohl** [comment]
There's a merge conflict now

**Comment by ehelms** [comment]
Thanks, fixed

**Review by ekohl — COMMENTED** [review]
Thinking more about this: should it actually be stored in the scenario itself rather than a separate marker file? For reference, how version locking stores its config:

https://github.com/theforeman/foreman-installer/blob/481ee53f04cbcc98fea39bba1a9c2c388bf22f1c/katello/hooks/pre_commit/09-version_locking.rb#L3-L9

I also don't know how well `configure_application` in a post hook behaves so I don't mind merging this and migrating later, but wanted to get your opinion first

**Comment by ehelms** [comment]
I think that is a good idea and I'd like to explore it when I have a bit more time so I filed https://projects.theforeman.org/issues/29262 to look into it. I'd like to go with this option for now as it restores prior behavior.

**Review by ekohl — APPROVED** [review]
Does this also need to be cherry picked into 2.0.0-rc3?

**Comment by ehelms** [comment]
Yea, we should for cleaner install messages.

**Pull request merged**
