### PR TITLE
Improve --reset-data hook

### PR DESCRIPTION
**Pull request by wbclark**
These are improvements that were worked on in https://github.com/theforeman/foreman-installer/pull/540 but no longer make sense in the context of that PR.

### CODE REVIEW

**Comment by wbclark** [comment]
https://github.com/theforeman/foreman-installer/pull/570 got merged while I was working on this.

I rebased to resolve the merge conflicts.

**Comment by ehelms** [comment]
Small nit to include that this adds content clearing to the pulp reset to the commit message

**Comment by wbclark** [comment]
> Small nit to include that this adds content clearing to the pulp reset to the commit message

Commit message is updated. Thanks!

**Comment by wbclark** [comment]
Split into 3 commits to better document each change.

**Review by ehelms — APPROVED** [review]

**Pull request merged**
