### PR TITLE
handle autosign change in puppet-puppet

### PR DESCRIPTION
**Pull request by mmoll**
disclaimer: I have no idea what I'm doing there :)

### CODE REVIEW

**Comment by mmoll** [comment]
would something like that work?

``` ruby
current_autosign=answers['puppet']['autosign']
answers['puppet'].delete('autosign') unless !!current_autosign == current_autosign
```

**Comment by domcleal** [comment]
Yes, that code snippet is probably preferable to keep any true/false values assigned to puppet::autosign.

Deleting and recomputing the value is probably OK, otherwise it means parsing it to split out the file mode into autosign_mode and expand `$confdir`.

**Comment by mmoll** [comment]
@domcleal Yes, I thought about that, but at the end of the day, as any string can be given, there might be also a path without mode (and maybe even something that's not coming to our mind now), so there would be additional logic needed to check this and split it differently.

Also I would need to read up, how to expand `$confdir / $dir`. ;)

**Comment by domcleal** [comment]
:+1: when tests pass.

**Comment by domcleal** [comment]
Thanks @mmoll!

**Pull request merged**
