### PR TITLE
Changing foreman api installer dependency

### PR DESCRIPTION
**Pull request by lzap**
No changelog change needed, right?

### CODE REVIEW

**Comment by domcleal** [comment]
No, that's ok.

And Debian :D

**Comment by lzap** [comment]
There you go.

I find strange missing foreman_api dependency there. Was proxy
registration ever working on Debians?

https://github.com/theforeman/foreman-packaging/pull/234

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
Sure, the dependency was installed by foreman_proxy.

**Comment by lzap** [comment]
Do I have go to rebase and merge then?

**Comment by domcleal** [comment]
This needs a rebase, but please don't merge as the underlying modules haven't been done.

**Comment by lzap** [comment]
Kay done.

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
Merged as 696e655, thanks.

**Pull request closed without merging**
