### PR TITLE
Disable repo management by default, rely on -release etc.

### PR DESCRIPTION
**Pull request by domcleal**
Untested!

### CODE REVIEW

**Comment by lzap** [comment]
WFM on Fedora 19! +1

**Comment by skottler** [comment]
Works for me as well. Merging!

**Comment by skottler** [comment]
Merged as 054658076675accb771960918fa7f2712cc9f603. Thanks @domcleal.

**Comment by ekohl** [comment]
Should this be mentioned in the documentation somewhere? I think it's mostly yum localinstall foreman-release && run installer and I doubt many use the installer from source (and not figure this out) so it should be fine.

**Comment by domcleal** [comment]
@ekohl yeah, it'd mostly be an issue if somebody cloned the installer repo.  Maybe an update to README's in order..

**Comment by lzap** [comment]
Backporting into RC1! Thanks.

**Comment by GregSutcliffe** [comment]
Did anyone test this on Debian before the gung-ho merge? If not I can do so today.

**Pull request closed without merging**
