### PR TITLE
Fixes #3069 - Config files packaging

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by domcleal** [comment]
:+1:

**Comment by domcleal** [comment]
Oh, could you add a %changelog entry and bump the release please?

**Comment by ares** [comment]
@domcleal like this?

**Comment by lzap** [comment]
ACK

**Comment by domcleal** [comment]
That's it!

**Comment by lzap** [comment]
Pushed with 03229fef6a0fc6c650fe9095d251b0d36508632d I also fixed changelog. Thanks.

**Pull request merged**
