### PR TITLE
Refs #25839 - Avoid storing puppetserver related versions

### PR DESCRIPTION
**Pull request by ekohl**
Depends on https://github.com/theforeman/puppet-puppet/pull/668

### CODE REVIEW

**Review by ehelms — APPROVED** [review]
Pending the puppet-puppet change

**Comment by mmoll** [comment]
@ekohl tests need updating I guess?

**Comment by ekohl** [comment]
I've changed the migrations to only wipe it if the key is present. This fixes the tests

**Comment by mmoll** [comment]
merged bedankt @ekohl!

**Pull request merged**
