### PR TITLE
Fixes #24628 - Change REX SSH dir to /var/lib/foreman-proxy

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Comment by tbrisker** [comment]
Should this also be CPed to 1.19-stable?

**Comment by ekohl** [comment]
Yes, 5d71785e858efadf9d5e9a231045d162757ae931

**Comment by ehelms** [comment]
@ekohl Does this migration need to happen in katello scenarios as well?

**Comment by ekohl** [comment]
Yes, PRs incoming.

**Pull request merged**
