### PR TITLE
Add azure_rm plugin

### PR DESCRIPTION
**Pull request by apuntamb**

### CODE REVIEW

**Review by tbrisker — COMMENTED** [review]
This is failing because of missing `azure_rm` plugin in https://github.com/theforeman/puppet-foreman/tree/master/manifests/plugin - considering azure plugin is no longer supported, should we replace it with azure_rm?

**Comment by apuntamb** [comment]
> This is failing because of missing `azure_rm` plugin in https://github.com/theforeman/puppet-foreman/tree/master/manifests/plugin - considering azure plugin is no longer supported, should we replace it with azure_rm?

Ahh Okk, but since our documentation has azure (older one) too, should we create a file there with azure_rm.pp? Or you think edit the existing one? Also, is there a script to create a new file under plugins directory?

**Comment by ekohl** [comment]
I think replacing the plugin we install in `puppet-foreman` is fine. It is the proper replacement.

**Comment by apuntamb** [comment]
> I think replacing the plugin we install in `puppet-foreman` is fine. It is the proper replacement.

How does this look: [puppet-foreman/767](https://github.com/theforeman/puppet-foreman/pull/767)?

**Comment by apuntamb** [comment]
@ekohl @tbrisker Since we are using the older azure installer option here: [puppet-foreman/767](https://github.com/theforeman/puppet-foreman/pull/767), should we close this PR?

**Comment by ekohl** [comment]
Yes, we can close this.

**Pull request closed without merging**
