### PR TITLE
[WIP] Switch to puppetlabs-apache

### PR DESCRIPTION
**Pull request by ekohl**
This is just a PR to make testing easier. Changing foreman and puppet repo URLs should not be needed in the final PR.

### CODE REVIEW

**Comment by lzap** [comment]
To test:

```
yum -y install http://yum.theforeman.org/nightly/el6/x86_64/foreman-release.rpm
yum -y install git ruby-devel rubygems make gcc rubygem-rake asciidoc rubygem-kafo rubygem-foreman_api
git clone https://github.com/ekohl/foreman-installer.git -b puppetlabs-apache
cd foreman-installer
git submodule init
git submodule update
rake build PREFIX=/usr SYSCONFDIR=/etc VERSION=$(git describe)
rake install PREFIX=/usr SYSCONFDIR=/etc VERSION=$(git describe)
foreman-installer -v
```

**Comment by lzap** [comment]
Okay does not work for me on RHEL 6.4:

```
[ERROR 2014-01-06 13:02:14 verbose]  Could not start Service[httpd]: Execution of '/sbin/service httpd start' returned 1: 
[ERROR 2014-01-06 13:02:14 verbose]  /Stage[main]/Apache::Service/Service[httpd]/ensure: change from stopped to running failed: Could not start Service[httpd]: Execution of '/sbin/service httpd start' returned 1: 
[ERROR 2014-01-06 13:02:15 verbose]  Could not start Service[httpd]: Execution of '/sbin/service httpd start' returned 1: 
[ERROR 2014-01-06 13:02:15 verbose]  /Stage[main]/Apache::Service/Service[httpd]/ensure: change from stopped to running failed: Could not start Service[httpd]: Execution of '/sbin/service httpd start' returned 1:
...
[ INFO 2014-01-06 13:02:19 verbose]  Class[Foreman_proxy::Service]: Scheduling refresh of Class[Foreman_proxy::Register]
[ERROR 2014-01-06 13:02:19 verbose]  Could not find a suitable provider for foreman_smartproxy
```

Apache does not come up:

```
Starting httpd: Syntax error on line 37 of /etc/httpd/conf.d/25-puppet.conf:
SSLCertificateChainFile: file '/var/lib/puppet/ssl/ca/ca_crt.pem' does not exist or is empty
```

**Comment by domcleal** [comment]
@lzap do you have the whole log?  Was Exec['puppet_server_config-generate_ca_cert'] evaluated after the error?

Maybe the relationship on puppet::server::passenger at the top of puppet/manifests/server/config.pp needs to change to apache or apache::service?

**Comment by domcleal** [comment]
Or perhaps anchor apache before puppet::server::passenger?

**Comment by ekohl** [comment]
That does sound like a dependency issue because it worked for me on CentOS 6.4.

**Comment by lzap** [comment]
http://sprunge.us/aRdM

**Comment by lzap** [comment]
Ok looks fine now, except the weird:

```
[ERROR 2014-01-07 08:31:47 verbose]  Could not find a suitable provider for foreman_smartproxy
```

**Comment by ekohl** [comment]
That sounds like the foreman_api package wasn't installed before the run and puppet failed to load it during. Maybe that doesn't work well with RPMs?

**Comment by domcleal** [comment]
Which version of Puppet was it?  2.7 upwards should be ok.. the debug at the end of the log seems to show it tried to reload the library but failed (foreman_api installed during the run):

<pre>
[DEBUG 2014-01-06 13:02:19 main]  Failed to load library 'foreman_api' for feature 'foreman_api'
[DEBUG 2014-01-06 13:02:19 main]  Puppet::Type::Foreman_smartproxy::ProviderRest: feature foreman_api is missing
</pre>

Does `ruby -rrubygems -e 'require "foreman_api"'` work (non-SCL)?

**Comment by lzap** [comment]
Yeah I was missing the foreman_api, I was just confused by puppet error message. Why puppet always report useless messages? :-)

+1 ALL GOOD :thumbsup: on RHEL 6.4/6.5

**Comment by domcleal** [comment]
Why was it missing?  It looks to have been installed.  This work shouldn't have changed it, but is it a concern?

**Comment by lzap** [comment]
Well my resolution was to install foreman_api RPM before running puppet.
I also noticed I am using Puppet installed from Rubygems (3.4.2), not
sure if that makes a difference. Maybe this rubygems puppet does not see
a system gem.

On Tue, Jan 07, 2014 at 03:13:46AM -0800, Dominic Cleal wrote:

> Why was it missing?  It looks to have been installed.  This work shouldn't have changed it, but is it a concern?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/theforeman/foreman-installer/pull/84#issuecomment-31729632

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by domcleal** [comment]
Debian 7 is fine.

pl-apache is broken though on F19, it's enabling modules by default which aren't present (and setting apache::default_mods => false will be tricky).  After removing three there (authz_default, authn_default, authn_alias) then I get MPM errors, probably because the module is breaking httpd.conf.  I can't see a way to disable that, and haven't looked into exactly what's needed yet.

**Comment by domcleal** [comment]
I think we should probably merge this, and release 1.4.0-RC1 with Fedora 19 issues as known, then work to resolve these in pl-apache before release.  If needs be, we can use a fork of pl-apache until PRs are accepted.

**Comment by ekohl** [comment]
Our supported platforms also include Ubuntu LTS and IIRC Debian 6. I think we should test those so we at least know if there are known issues before merging.

Maybe redundant, but I'd like to mention that this PR should not be merged until the other PRs are merged and this is updated to not change the foreman and puppet module URLs.

**Comment by stbenjam** [comment]
There's multiple issues overall with pl-apache, it's just not compatible with Fedora 19 or it's version of Apache. :-\
- SSLMutex is depcreated in Apache > 2.2
- Various modules need to be not used (auth\* as @domcleal noted)
- The conf.modules.d directory needs to be Included in httpd.conf

Hacks to get it to work right on F19:
  https://github.com/stbenjam/puppetlabs-apache/compare/fedora19-fixes

(Also, I needed to add  Options FollowSymLinks to <Directory /usr/share/foreman/public> in 5-foreman-ssl.conf, since on my box public came up as a symlink...)

**Comment by stbenjam** [comment]
Not sure what you want to do then about it -- of course the right solution is to properly fix up puppetlabs-apache for F19, but they're not taking PR's? 

I could clean up my hacks and make it nicer and give you a patch to apply in the foreman-installer until it's in the upstream puppetlabs-apache repo.

**Comment by ekohl** [comment]
@stbenjam thank you for testing and coming up with patches! Is there are particular reason you sometimes check with `!=` and sometimes `>=`?

And they are taking PR's, just not as fast as you sometimes want. I would find it perfectly acceptable to merge puppetlabs-apache into theforeman-apache as a separate branch where we bundle all fixes we need till they are resolved upstream. For most cases users basing on puppetlabs-apache would already be a benefit.

**Comment by stbenjam** [comment]
operatingsystemrelease is a string.  I did the ERB's first and used >=. Does the Puppet DSL support .to_i? I didn't think it did.

Anyway, it doesn't matter, that branch I gave is not really a usable fix, it was just to show what was wrong with pl-apache.

Do you want the right fix in pl-apache? I'll clean it up tonight into something presentable if so.

**Comment by ekohl** [comment]
Not sure about .to_i. Can't find anything.

I'd prefer if fixes went straight to pl-apache because I see maintaining a fork as a workaround to release faster.

**Comment by stbenjam** [comment]
Ok, so the fork should be under the foreman account? If you create the fork I'll submit an PR.

**Comment by domcleal** [comment]
Tested successfully on Ubuntu 12.04, with a small patch to puppet-foreman (see PR there).  I can't test squeeze, perhaps @GregSutcliffe can?

**Comment by ekohl** [comment]
@stbenjam I don't really care on which account the fork is created. I think most of us have created forks under our own accounts and only forked to theforeman if we need it for a longer period.

**Comment by stbenjam** [comment]
@ekohl Ok then. I opened a PR for foreman-installer to use my fork: #87

I  also submitted an issue and PR for the SSLMutex issue to puppetlabs-apache, which is the only one they didn't already know about.

**Comment by domcleal** [comment]
@ekohl when you're ready, could you please rebase this PR and update it to include @stbenjam's fork?  We can try running it through BATS then to confirm all is good.  I think we also need the puppet-foreman evil.

**Comment by ekohl** [comment]
@domcleal updated. It also includes an updated puppet-foreman.

**Comment by ekohl** [comment]
On Debian 7 and Precise I now get errors when running with foreman-bats:

```
Invalid parameter apache_conf_dir on node foreman-precise.example.com
```

**Comment by domcleal** [comment]
@ekohl this turned out to be a kafo bug (https://github.com/theforeman/kafo/pull/55) which meant the modules_dir wasn't obeyed, so it was reading the parameters out of /usr/share/foreman-installer/modules.  Fixed in 0.3.6, so should pass on Debian now.

Watching http://ci.theforeman.org/view/Installer/job/systest_foreman_matrix/2/, but I'm expecting it to pass.

**Comment by GregSutcliffe** [comment]
```
I can't test squeeze, perhaps @GregSutcliffe can?
```

@domcleal sorry, I lost track of all these changes while working on other stuff. I'll happily test on squeeze later today - do I just need to run this branch of the installer (i.e it poits to the right branches of other stuff) or is there more to it?

**Comment by domcleal** [comment]
Don't worry, Jenkins will test it.

**Comment by domcleal** [comment]
We have PASS on all platforms ([el6 retest due to SEGV](http://ci.theforeman.org/job/systest_foreman/86/)), except f19 which is issues with BATS and other bugs.

Let's merge the other two PRs now.

**Comment by domcleal** [comment]
Merged as 03ef212, updated to point at theforeman repos.  Thanks @ekohl, this rocks - excellent work!

**Comment by ekohl** [comment]
Thank you all for all the testing as well!

**Comment by vmadman** [comment]
> Why was it missing? It looks to have been installed. This work shouldn't have changed it, but is it a concern? - https://github.com/theforeman/foreman-installer/pull/84#issuecomment-31729632

I had trouble following this issue thread because it seems to have one or more other topics within, so I'm not even sure if I'm in the right place for this.  Anyway, this seems a bit odd to me:

> Well my resolution was to install foreman_api RPM before running puppet...

So, is it an acceptable condition to need to install foreman_api before running puppet?  That's weird, right?

I'm hitting the same, or a similar error:

```
Error: Could not find a suitable provider for foreman_smartproxy
```

My log is set to Notice, so I do not have the extra debug info at this time, but I would assume it is identical to @lzap 's.

Anyone have any ideas for another solution to this?

```
[luke@vagrant ~]# cat /etc/redhat-release
CentOS release 6.4 (Final)

[luke@vagrant ~]# puppet --version
3.4.3

[luke@vagrant ~]# ruby --version
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
```

See also: https://groups.google.com/forum/#!topic/foreman-users/u3peMoo2FA0

**Comment by ekohl** [comment]
@vmadman I think it's unrelated to this particular PR and that the conversation should be continued on the mailing list.

**Pull request closed without merging**
