### PR TITLE
Updated all the submodule to use the latest versions and added the option to run puppet to generate_answers.rb

### PR DESCRIPTION
**Pull request by skottler**

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
@skottler diff looks fine, but your commit history looks a mess - rebase?

**Comment by skottler** [comment]
Thanks for the new @GregSutcliffe - diffed and rebased :+1:

**Comment by GregSutcliffe** [comment]
@skottler perfect! @domcleal should probably get all 3 of us on board before we release 1.1 - you good to merge and cut?

**Comment by domcleal** [comment]
I'd really like to get https://github.com/theforeman/puppet-foreman/pull/32 merged first, since we currently have cron duplication between the packages and modules.  The debs and RPMs should have identical cron configurations already.

Otherwise, yes, we should merge.  I'll do a full run through on EL6 just to be sure, but afaik it's stable.

**Comment by skottler** [comment]
I've merged theforeman/puppet-foreman#32 and updated the submodule.

**Comment by domcleal** [comment]
:+1: all-in-one test was successful, merge and ship it!

**Pull request merged**
