### PR TITLE
Add foreman_snapshot_management plugin

### PR DESCRIPTION
**Pull request by mdellweg**

### CODE REVIEW

**Comment by ekohl** [comment]
Given this plugin is in the katello repository and needs Katello installed I think that the katello scenario in `katello-installer` is a better fit.

**Comment by mdellweg** [comment]
@ekohl i'm sorry, but I think you confused something: This plugin does not depend on Katello.
I guess you thought about `foreman_scc_manager`.

**Review by ekohl — APPROVED** [review]
You are right, I was thinking of the wrong plugin.

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
