### PR TITLE
Add ForemanLeapp plugin

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by ehelms** [comment]
Howdy @stejskalleos , you'll want to add this to katello-answers.yaml as well. And create a migration to ensure ugprades have this available. There is a helper in `bin/` to help with this.

**Comment by ekohl** [comment]
The tests will also fail until https://github.com/theforeman/puppet-foreman/pull/833 is merged.

**Comment by stejskalleos** [comment]
Updated `katello-answers.yaml` and rebased.

**Review by ekohl — CHANGES_REQUESTED** [review]
You missed the katello migration. Note the naming conventions are slightly different for the two, but the `create-migration` script takes care of it. You can even echo the actual migration to stdin to ensure the content is the same.

**Comment by stejskalleos** [comment]
[test continuous-integration/travis-ci/pr]

**Comment by ekohl** [comment]
I think you need to modify https://github.com/theforeman/foreman-installer/blob/develop/spec/fixtures/pulpcore-migration/katello-answers-after.yaml as well

**Review by ekohl — APPROVED** [review]

**Pull request merged**
