### PR TITLE
Fixes #29097: Move puppet-agent-oauth reinstall to Foreman hooks

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
I actually like this hook because it provides a nice guarantee that the gem actually works in that env. We also still support upgrading from Puppet 5 to Puppet 6 where this is needed. IMHO this should be moved to the general hooks.

**Comment by ehelms** [comment]
Moved to main hooks and stopped it form outputting the check for the package.

**Review by ekohl — APPROVED** [review]
Code wise I think this is ok, but please have a look at the commit message and PR summary. I think generalizing it to all scenarios is more important than the output handling.

**Comment by ehelms** [comment]
Updated commit and PR message

**Review by ekohl — APPROVED** [review]
I think this safely falls back on Debian since the `rpm` command will simply fail. Ideally we'd also have a check that uses `dpkg` and if so, executes the right `apt` command but let's consider that out of scope for now.

**Pull request merged**
