### PR TITLE
Pin puppetdb for Puppet 5 compatibility

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Review by tbrisker — APPROVED** [review]
Thanks @ekohl !

**Comment by tbrisker** [comment]
looks like 7.0.1 has been released with the dependency fix, shall we revert this commit now?

**Comment by ekohl** [comment]
Yup, I'll send a PR

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-installer/pull/285

**Pull request merged**
