### PR TITLE
Refs #36843: Pass array to capture2e as arguments

### PR DESCRIPTION
**Pull request by ehelms**
(cherry picked from commit 66c84d2278857a1261ed3b01f2249111af1828ff)

### CODE REVIEW

**Comment by ehelms** [comment]
[test foreman-installer]

**Comment by ehelms** [comment]
[test foreman-installer]

**Comment by ehelms** [comment]
[test foreman-installer]

**Review by evgeni — APPROVED** [review]

**Review by ekohl — APPROVED** [review]
Packit failure is because it's not correctly configured: https://github.com/theforeman/foreman-installer/pull/906

**Pull request merged**
