### PR TITLE
Remove sudo requirement from generate_answers, only run Puppet if root

### PR DESCRIPTION
**Pull request by domcleal**
Minimal OS installs don't have sudo.

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
Looks fine to me. @skottler can we get this in before you cut a release?

**Comment by skottler** [comment]
Yep - has this already been tested or should I do that before merge?

**Comment by domcleal** [comment]
I haven't actually run the code, just tested euid returns what I expected.

**Comment by GregSutcliffe** [comment]
I have a clean Squeeze VM here, gimme 5min

**Comment by GregSutcliffe** [comment]
Works as expected on Squeeze. Ship it @domcleal

**Comment by domcleal** [comment]
Thanks for testing @GregSutcliffe !

**Pull request merged**
