### PR TITLE
Rely on puppet-candlepin for cpdb execution

### PR DESCRIPTION
**Pull request by ekohl**
Draft because it includes https://github.com/theforeman/foreman-installer/pull/417 and relies on https://github.com/theforeman/puppet-candlepin/pull/139.

### CODE REVIEW

**Comment by ekohl** [comment]
@ehelms with the Foreman DB migration work added we can remove the `--upgrade` flag on this and make it a regular hook. We should check if `postgresql-server` is installed prior to running it.

**Comment by ehelms** [comment]
You can take this out of draft and I think it's good to go. I would not drop the upgrade hook here due to postgres upgrades.

**Comment by ekohl** [comment]
Rebased. Still depends on https://github.com/theforeman/puppet-candlepin/pull/139 to be merged first so for now still a draft.

**Review by ehelms — APPROVED** [review]
I'm monitoring current nightly with some fixes that have been merged. I'll merge this once I think its in a good place.

**Pull request merged**
