### PR TITLE
Release 3.5.2

### PR DESCRIPTION
**Pull request by ehelms**
Draft as I would like https://github.com/theforeman/foreman-installer/pull/831 to go in before release

### CODE REVIEW

**Comment by ehelms** [comment]
Do you think https://github.com/theforeman/puppet-foreman/pull/1108 is includable in 3.5.2 if we get it merged? I can do the leg work

**Comment by ehelms** [comment]
Unless you think https://github.com/theforeman/puppet-foreman/pull/1108 is close, I would have us proceed with this release.

**Comment by ekohl** [comment]
I do think that's close, so let's wrap it up.

**Comment by ehelms** [comment]
This has two commits added that bring in the fixes in puppet-foreman and puppet-puppet.

**Review by ekohl — APPROVED** [review]

**Comment by ehelms** [comment]
Are there additional changes staged up for a 3.5.2 release? Or would it be possible to at least get a foreman-installer 3.5.2 source generated?

**Pull request merged**
