### PR TITLE
Fixes #34440 - skip upgrade:run by run_rake_upgrade=false

### PR DESCRIPTION
**Pull request by evgeni**
this allows to override it in certain scenarios

### CODE REVIEW

**Comment by evgeni** [comment]
Or should this be inverted? "skip_rake_upgrade", then only special scenarios need to set it?

**Comment by evgeni** [comment]
So I didn't manage to set this via `/usr/share/foreman-installer/config/foreman.hiera/scenario/${scenario}/scenario-overrides.yaml`, but `/etc/foreman-installer/scenarios.d/${scenario}.yaml` works and is sufficient for my needs.

@ekohl thoughts?

**Review by ekohl — COMMENTED** [review]
I'm not a fan of negative named values because you can get double negatives. However, `get_custom_config` doesn't have a `default` parameter so you'll get ugly code.

The alternative is to merge + release https://github.com/theforeman/kafo/pull/346 and then use `get_custom_config(:rake_upgrade, true)`. I want to do a release anyway to be able to use the `Sensitive` data type so it wouldn't be a huge deal.

I could be OK with merging this, but also wouldn't mind a more elegant solution. Thoughts?

**Comment by evgeni** [comment]
I would prefer a solution that doesn't require a Kafo patch ;-)

```ruby
def should_run_rake_upgrade?
  it = get_custom_config(:rake_upgrade)
  it.nil? ? true : it
end
```

Would that do the same?

**Comment by ekohl** [comment]
Yes it would. You can also write the last line as `it.nil? || it` but that's a trivial difference.

**Comment by evgeni** [comment]
Updated (I went with my line, as I find it expresses the desire behind it a bit clearer)

**Review by ekohl — APPROVED** [review]

**Pull request merged**
