### PR TITLE
Bump module for bugfix in puppetlabs/puppetlabs-postgresql@2718f14

### PR DESCRIPTION
**Pull request by lattwood**
foreman-installer fails to install on Amazon Linux because it ships with postgresql9, and the module assumes Postgresql 8 on RHEL variants.

### CODE REVIEW

**Comment by domcleal** [comment]
We need to bump this along with puppet-foreman for support of this new version of puppetlabs-postgresql, since we haven't done this yet.  I'll be submitting a PR shortly for an update of puppet-foreman anyway, will be sure to include this.

**Comment by ekohl** [comment]
@domcleal didn't we already do that in https://github.com/theforeman/puppet-foreman/commit/b22f96ffd533f7920027d6f91b8cebcddf8bcbf9?

**Comment by domcleal** [comment]
@ekohl yep, but we haven't bumped the submodule to include that yet

**Comment by ekohl** [comment]
Closed in favour of https://github.com/theforeman/foreman-installer/pull/88.

**Pull request closed without merging**
