### PR TITLE
Refs #29814: Check that cdn-ssl answer exists

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Why is this needed? There's also an else branch that could simply be removed.

**Comment by ehelms** [comment]
On a fresh install, the answers file is unexpanded and this value does not
exist. Results in an undefined method [] for True class.

**Comment by sthirugn** [comment]
ACK!

I got this error in nightly that blocks the installation. I can confirm that this patch fixed it and the installation is successful now.

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
for reference, the current traceback in nightly:

```
    /usr/share/foreman-installer/katello/hooks/pre_commit/14-cdn_setting.rb:5:in `block (4 levels) in load': undefined method `[]' for true:TrueClass (NoMethodError)
            from /usr/share/gems/gems/kafo-4.0.1/lib/kafo/hooking.rb:34:in `instance_eval'
            from /usr/share/gems/gems/kafo-4.0.1/lib/kafo/hooking.rb:34:in `block (4 levels) in load'
            from /usr/share/gems/gems/kafo-4.0.1/lib/kafo/hook_context.rb:16:in `instance_exec'
            from /usr/share/gems/gems/kafo-4.0.1/lib/kafo/hook_context.rb:16:in `execute'
            from /usr/share/gems/gems/kafo-4.0.1/lib/kafo/hooking.rb:51:in `block in execute'
            from /usr/share/gems/gems/kafo-4.0.1/lib/kafo/hooking.rb:49:in `each'
            from /usr/share/gems/gems/kafo-4.0.1/lib/kafo/hooking.rb:49:in `execute'
            from /usr/share/gems/gems/kafo-4.0.1/lib/kafo/kafo_configure.rb:150:in `execute'
            from /usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:63:in `run'
            from /usr/share/gems/gems/kafo-4.0.1/lib/kafo/kafo_configure.rb:118:in `run'
            from /usr/share/gems/gems/clamp-1.1.2/lib/clamp/command.rb:132:in `run'
            from /usr/share/gems/gems/kafo-4.0.1/lib/kafo/kafo_configure.rb:162:in `run'
            from /sbin/foreman-installer:8:in `<main>'
```

**Pull request merged**
