### PR TITLE
Refs #32078 - Update theforeman/foreman_proxy to 17.1.1

### PR DESCRIPTION
**Pull request by ekohl**
This pulls in the explicit dynflow core service notifications to fix missing restarts.

### CODE REVIEW

**Review by evgeni — APPROVED** [review]

**Comment by ekohl** [comment]
[test foreman-installer]

**Comment by ekohl** [comment]
The issue looks persistent but Jenkins doesn't archive the log file with the error.

**Comment by ehelms** [comment]
[test foreman-installer]

**Comment by ehelms** [comment]
I think this caused by the release of `kafo_parsers`:

```
Error: Evaluation Error: Error while evaluating a Function Call, 'downcase' parameter 'arg' expects a value of type Numeric, String, Array, or Hash, got Undef (file: /home/ehelms/workspace/upstream/foreman-installer/2.5-6.0/share/foreman-installer/modules/foreman/manifests/params.pp, line: 3, column: 17) on node 
```

The version of kafo_parsers for which this is broken is not released in this branch so we can pin the version here to get past this and match packaging. I'm looking into the breakage.

**Comment by ehelms** [comment]
Ahh actually, this is related to facter. 4.0.52 appears to have broken this in my local testing.

**Comment by ekohl** [comment]
I've pushed a commit to test this theory out. Not sure if we should merge it, but I want to know what CI says with it.

**Comment by ehelms** [comment]
This error does not appear in the terminal or in the log files. The reason for this is we do not setup logging when running `--help` to prevent log file sprawl. The downside to this is that we are not at least setting up terminal logging at an error level to spit out error when running `--help`. I'll work on a fix for this if we agree that we should make this change due to an issue like this.

**Comment by ekohl** [comment]
Perhaps it should still setup logging on the console but not the log file when running `--help`.

**Comment by ekohl** [comment]
I've created https://github.com/theforeman/foreman-installer/pull/663 against develop so we can cherry pick it here.

**Comment by ehelms** [comment]
Here is a follow up in Kafo to display this error in the future: https://github.com/theforeman/kafo/pull/328

**Comment by ekohl** [comment]
Updated to use the cherry picked commit.

**Review by ehelms — APPROVED** [review]

**Pull request merged**
