### PR TITLE
Refs #26563, #26571 - cherry picks for 1.21.3

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Review by chris1984 — APPROVED** [review]

**Comment by ehelms** [comment]
Is https://github.com/theforeman/puppet-katello/pull/283 also needed to complete this?

**Comment by ekohl** [comment]
Yes it is.

**Comment by jturel** [comment]
This should be good once updated with a new puppet-katello

**Comment by ekohl** [comment]
Updated, now with katello/katello 9.0.2.

**Pull request merged**
