### PR TITLE
Fixes #25590 - Enable installer support for HTTPBoot

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
@lzap given your concerns about HTTPBooting, do we want to cherry pick this into 1.20?

**Review by lzap — COMMENTED** [review]
I think that HTTPBoot is not in good enough shape, therefore no need to cherry pick. Thanks for the headsup.

**Comment by ekohl** [comment]
Thanks for the confirmation. Closing this then.

**Comment by lzap** [comment]
Thanks!

**Pull request closed without merging**
