### PR TITLE
2.5 puppet module updates for Pulp 3.14

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Linking back to another PR that should be merged together: https://github.com/theforeman/forklift/pull/1379

Then another thing we must not forget is to add a Conflict on pulpcore < 3.14 in the foreman-installer-katello RPM.

**Comment by evgeni** [comment]
Given https://community.theforeman.org/t/katello-nightly-rpm-pipeline-1027-failed/24403, I am not sure that including puppet-pulpcore 4.0.0 is a good idea, as this will break proxy setups.

**Comment by ehelms** [comment]
This is updated to include puppet-pulpcore 4.0.1 which fixes the Redis issue.

**Review by evgeni — APPROVED** [review]
ACK as this now contains `theforeman-pulpcore (4.0.1)` :)

**Pull request merged**
