### PR TITLE
Fixes #35899, 35925 - Mosquitto tuning and SSH keep alive

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]

**Review by ekohl — CHANGES_REQUESTED** [review]
I just realized: we never wrote the migration for SSH keepalive.In https://github.com/theforeman/puppet-foreman_proxy/pull/795#pullrequestreview-1244079040 I mentioned this.

Without the migration only new installations will get the SSH keepalive options.

**Comment by ehelms** [comment]
> I just realized: we never wrote the migration for SSH keepalive.In [theforeman/puppet-foreman_proxy#795 (review)](https://github.com/theforeman/puppet-foreman_proxy/pull/795#pullrequestreview-1244079040) I mentioned this.
> 
> Without the migration only new installations will get the SSH keepalive options.

Proposed -- https://github.com/theforeman/foreman-installer/pull/833

**Comment by ehelms** [comment]
This now includes a cherry pick of #833

**Review by ekohl — APPROVED** [review]
Thanks! I don't know how well the bot parses the multiple fixes, but we'll see.

**Pull request merged**
