### PR TITLE
Fixes #28335 - Add CLI option for Foreman AzureRM

### PR DESCRIPTION
**Pull request by apuntamb**

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
CI will fail until https://github.com/theforeman/puppet-foreman/pull/772 is merged.

Can you also add it to the katello scenario?

**Comment by apuntamb** [comment]
> CI will fail until [theforeman/puppet-foreman#772](https://github.com/theforeman/puppet-foreman/pull/772) is merged.
> 
> Can you also add it to the katello scenario?

Sure thing.

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Mind creating a Redmine issue under the installer project? I'd prefer that since we'll cherry pick this into 1.24.

**Comment by apuntamb** [comment]
> Mind creating a Redmine issue under the installer project? I'd prefer that since we'll cherry pick this into 1.24.

Related Redmine issue: [#28335](https://projects.theforeman.org/issues/28335)

**Comment by ekohl** [comment]
I should be more explicit :) You can use `Fixes #28335` in the commit message here in the exact same way as the core repo. Would you mind doing so? After that I'll merge and cherry pick to 1.24 so it'll be part of RC3.

**Comment by apuntamb** [comment]
> I should be more explicit :) You can use `Fixes #28335` in the commit message here in the exact same way as the core repo. Would you mind doing so? After that I'll merge and cherry pick to 1.24 so it'll be part of RC3.

Okay got it. I have just changed the title here, let me modify my commit message too. Thanks for the clarification.

**Comment by apuntamb** [comment]
Updated pr with new commit message linked to redmine issue. :)

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
