### PR TITLE
Enable foreman_proxy::realm_split_config_files for 1.15

### PR DESCRIPTION
**Pull request by domcleal**
After https://github.com/theforeman/puppet-foreman_proxy/pull/327.

### CODE REVIEW

**Comment by ekohl** [comment]
I'm guessing the differing defaults (true here vs false in the module) are intentional

**Comment by domcleal** [comment]
Yes, as the `develop` branch here is specifically to be used with version 1.15 (same as f777323).

The module default could be true for 1.15 too, but I think we've been too aggressive in defaulting parameters to support unreleased versions, so it's false.

**Review by ekohl — APPROVED** [review]
I had the same thought process

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Pull request merged**
