### PR TITLE
Update to puppetlabs-stdlib 9.x

### PR DESCRIPTION
**Pull request by ekohl**
Needs:

* https://github.com/theforeman/puppet-candlepin/pull/239
* https://github.com/theforeman/puppet-foreman/pull/1125
* https://github.com/theforeman/puppet-foreman_proxy_content/pull/453
* https://github.com/theforeman/puppet-katello/pull/482
* https://github.com/theforeman/puppet-puppet/pull/898
* https://github.com/theforeman/puppet-qpid/pull/186

And a round to update extlib:

* https://github.com/theforeman/puppet-candlepin/pull/246
* https://github.com/theforeman/puppet-certs/pull/437
* https://github.com/theforeman/puppet-foreman/pull/1138
* https://github.com/theforeman/puppet-foreman_proxy/pull/818
* https://github.com/theforeman/puppet-foreman_proxy_content/pull/463
* https://github.com/theforeman/puppet-katello/pull/483
* https://github.com/theforeman/puppet-pulpcore/pull/314

And possibly more.

### CODE REVIEW

**Comment by ekohl** [comment]
```
F, [2023-11-07T16:38:22.595255 #24758] FATAL -- : Unable to parse /home/jenkins/workspace/foreman-installer-pr-test/_build/modules/foreman_proxy/manifests/plugin/dns/infoblox.pp because of: unknown data type Stdlib::Ip::Address
```

This is a problem introduced in puppetlabs-stdlib 9.0.0. https://github.com/puppetlabs/puppetlabs-stdlib/pull/1406 should address this.

I'd have thought https://github.com/theforeman/kafo_module_lint would have caught this in CI, so perhaps we're not running it (properly) in puppet-foreman_proxy..

**Comment by evgeni** [comment]
I don't think we run module lint (anymore)

**Comment by evgeni** [comment]
But also, if Puppet doesn't care, why should Kafo?

**Comment by ekohl** [comment]
Perhaps that's an implementation detail, but for now I think the fastest fix is to make it consistent.

**Comment by ekohl** [comment]
[test foreman-installer]

**Comment by ekohl** [comment]
I thought 9.4.1 would have been released, since it's @ https://forge.puppet.com/modules/puppetlabs/stdlib but librarian hasn't found it yet. Could be a cache somewhere.
```
[Librarian]   Module puppetlabs-stdlib found versions: 9.4.0, 9.3.0, 9.2.0, 9.1.0, 9.0.0, 8.6.0, 8.5.0, 8.4.0, 8.3.0, 8.2.0, 8.1.0, 8.0.0, 7.1.0, 7.0.1, 7.0.0, 6.6.0, 6.5.0, 6.4.0, 6.3.0, 6.2.0, 6.1.0, 6.0.0, 5.2.0, 5.1.0, 5.0.0, 4.25.1, 4.25.0, 4.24.0, 4.23.0, 4.22.0, 4.21.0, 4.20.0, 4.19.0, 4.18.0, 4.17.1, 4.17.0, 4.16.0, 4.15.0, 4.14.0, 4.13.1, 4.13.0, 4.12.0, 4.11.0, 4.10.0, 4.9.1, 4.9.0, 4.8.0, 4.7.0, 4.6.0, 4.5.1, 4.5.0, 4.4.0, 4.3.2, 4.3.0, 4.2.2, 4.2.1, 4.2.0, 4.1.0, 3.2.2, 3.2.1, 3.2.0, 3.1.1, 3.1.0, 3.0.1, 3.0.0, 2.6.0, 2.5.1, 2.5.0, 2.4.0, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.1, 2.2.0, 2.1.3, 2.0.0, 1.1.0, 1.0.0, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1
```

**Comment by evgeni** [comment]
[test foreman-installer]

**Comment by evgeni** [comment]
```
FATAL -- : Unable to parse /home/jenkins/workspace/foreman-installer-pr-test/_build/modules/foreman_proxy/manifests/plugin/dns/infoblox.pp because of: data type not recognized Variant[
rake aborted!
```

This is new

**Comment by evgeni** [comment]
Aaand multi line definitions strike again!
https://github.com/puppetlabs/puppetlabs-stdlib/blob/main/types/ip/address.pp

```
type Stdlib::IP::Address = Variant[
  Stdlib::IP::Address::V4,
  Stdlib::IP::Address::V6,
]
```

😞

**Comment by evgeni** [comment]
https://github.com/theforeman/kafo/pull/367

**Comment by ekohl** [comment]
Now updated with a dependency on kafo 7.3+

**Review by evgeni — APPROVED** [review]

**Comment by ekohl** [comment]
COPR fails because it doesn't have Kafo 7.3.0: https://github.com/theforeman/foreman-packaging/pull/9966 & https://github.com/theforeman/foreman-packaging/pull/9967

**Comment by evgeni** [comment]
Yeah, don't mind copr/packit IMHO :)

**Comment by ekohl** [comment]
I was waiting for those to build so the nightly package would also be built. That is the case now.

**Pull request merged**
