### PR TITLE
Fixes #32914 - add puppet plugin to answer files

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Would you mind filing a Redmine issue for this? I think this may need to be cherry picked into 2.5.

**Comment by ezr-ondrej** [comment]
> need to be cherry picked into 2.5

I'd not do that. For 2.5 the plugin was only for testing purposes, so it's ok there needed to be manual work done outside of installer. Given we would add that only in 2.5.2 I don't see a reason to, unless there are internal reasons :)

**Review by ekohl — APPROVED** [review]

**Review by ekohl — APPROVED** [review]
Test failure is expected.

**Comment by ehelms** [comment]
I'd think we would want a migration as well to ensure the puppet plugin exists on upgraded machines.

**Comment by ekohl** [comment]
Oh, that's a good point. Thanks for that.

**Pull request merged**
