### PR TITLE
Fixes #19986 - Ensure the puppet user exists

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ehelms** [comment]
This looks good to me from a code perspective.

**Comment by ekohl** [comment]
I'm doing a plain pipeline install because I recall that could reproduce it. If it helps there, then I'll test it with the patch.

**Comment by ekohl** [comment]
@ehelms pointed out to me this might have already been fixed. I did find https://docs.puppet.com/puppet/4.10/release_notes.html#bug-fixes-3 which states:

> On CentOS 7, Puppet could not create a user and set the owner of a file to that user in the same run. This was a regression introduced in 4.10.2 and 5.0.0.

I'm not sure if that was the actual bug or not.

**Comment by ekohl** [comment]
It appears it was fixed in puppetserver 2.8.0 with the automatic CRL refresher. See https://docs.puppet.com/puppetserver/2.8/release_notes.html#new-feature-automatic-crl-refresh-on-certificate-revocation

**Comment by mmoll** [comment]
AFAICT we don't enable this on puppetserver 2.x. And as it's only working with Java 8 I guess there's no easy way to just enable it always with 2.x

**Comment by ekohl** [comment]
I assume there are unrelated changes that ensure hostcrl has the correct permissions because I was no longer able to reproduce the issue:

```
[root@pipeline-katello-nightly-centos7 foreman-installer]# grep crl.pem *
katello.log:"::foreman::params::server_ssl_crl": "/etc/puppetlabs/puppet/ssl/crl.pem"
katello.log:[DEBUG 2017-10-05 09:48:19 main]  Using settings: adding file resource 'hostcrl': 'File[/etc/puppetlabs/puppet/ssl/crl.pem]{:path=>"/etc/puppetlabs/puppet/ssl/crl.pem", :mode=>"644", :owner=>"root", :ensure=>:file, :loglevel=>:debug, :links=>:follow, :backup=>false}'
katello.log:[DEBUG 2017-10-05 09:48:19 main]  /File[/etc/puppetlabs/puppet/ssl/crl.pem]/seluser: Found seluser default 'system_u' for /etc/puppetlabs/puppet/ssl/crl.pem
katello.log:[DEBUG 2017-10-05 09:48:19 main]  /File[/etc/puppetlabs/puppet/ssl/crl.pem]/selrole: Found selrole default 'object_r' for /etc/puppetlabs/puppet/ssl/crl.pem
katello.log:[DEBUG 2017-10-05 09:48:19 main]  /File[/etc/puppetlabs/puppet/ssl/crl.pem]/seltype: Found seltype default 'puppet_etc_t' for /etc/puppetlabs/puppet/ssl/crl.pem
katello.log:[DEBUG 2017-10-05 09:48:19 main]  /File[/etc/puppetlabs/puppet/ssl/crl.pem]/selrange: Found selrange default 's0' for /etc/puppetlabs/puppet/ssl/crl.pem
katello.log:[DEBUG 2017-10-05 09:48:19 main]  /File[/etc/puppetlabs/puppet/ssl/crl.pem]: Adding autorequire relationship with File[/etc/puppetlabs/puppet/ssl]
katello.log:[DEBUG 2017-10-05 09:48:19 main]  /File[/etc/puppetlabs/puppet/ssl/crl.pem]/owner: owner changed 'puppet' to 'root'
[root@pipeline-katello-nightly-centos7 foreman-installer]# ls -l /etc/puppetlabs/puppet/ssl/crl.pem
-rw-r--r--. 1 puppet puppet 1011  5 okt 09:48 /etc/puppetlabs/puppet/ssl/crl.pem
[root@pipeline-katello-nightly-centos7 foreman-installer]# stat /etc/puppetlabs/puppet/ssl/crl.pem
  File: ‘/etc/puppetlabs/puppet/ssl/crl.pem’
  Size: 1011      	Blocks: 8          IO Block: 4096   regular file
Device: fd00h/64768d	Inode: 101048686   Links: 1
Access: (0644/-rw-r--r--)  Uid: (  992/  puppet)   Gid: (  989/  puppet)
Context: system_u:object_r:puppet_etc_t:s0
Access: 2017-10-05 09:48:07.552489238 +0000
Modify: 2017-10-05 09:48:02.329502314 +0000
Change: 2017-10-05 09:48:28.507436780 +0000
 Birth: -
```

**Pull request closed without merging**
