### PR TITLE
Fixes #26282 - Update to Kafo 3

### PR DESCRIPTION
**Pull request by ekohl**
Not sure why it's not working yet.

### CODE REVIEW

**Comment by ekohl** [comment]
Forklift config:

```yaml
centos7-foreman-puppet-6:
  box: centos7-foreman-nightly
  ansible:
    variables:
      koji_task_ids:
        - 178521 # kafo
        - 178533 # foreman-installer
      puppet_repositories_version: 6
```

**Review by ehelms — APPROVED** [review]
Needs rebase and tests passing. Any upgrade implications?

**Comment by ekohl** [comment]
Tests won't pass until a Kafo 3.0 gem is released. I think all issues have been fixed but going to do a last test run today. As long as we merge https://github.com/theforeman/foreman-packaging/pull/3500 there should be no upgrade concerns.

**Comment by ekohl** [comment]
Rebased

**Pull request merged**
