### PR TITLE
Add ACD plugin

### PR DESCRIPTION
**Pull request by sbernhard**
* foreman ACD plugin
 * smart proxy ACD plugin

### CODE REVIEW

**Comment by sbernhard** [comment]
tests are failing because something else...

**Review by ekohl — CHANGES_REQUESTED** [review]
You can call `./bin/create-migration` with multiple arguments and it'll create files with the same timestamps. This makes it clear that it's really the same migration.

You can also do both steps in a single file for `foreman.migrations` and `katello.migrations`.

The failure is resolved by https://github.com/theforeman/foreman-installer/pull/687 but there's one last thing I need to check with it. You can ignore it.

**Comment by sbernhard** [comment]
Thanks @ekohl for your feedback. I hope I did all the requested changes.

**Review by ekohl — APPROVED** [review]
Thanks!

**Pull request merged**
