### PR TITLE
Fixes #30006 - Remove MongoDB Storage Engine Migration Hook

### PR DESCRIPTION
**Pull request by wbclark**

### CODE REVIEW

**Comment by ekohl** [comment]
I wonder if we should start a Remove Pulp 2 tracker

**Comment by ehelms** [comment]
A tracker for Pulp 2 removal will be good across installer and packaging. I think this can fall under hooks and just get it's own issue. If you haven't upgraded mongodb storage engine by now... oh well.

**Comment by ekohl** [comment]
I still think this deserves a Redmine issue just to track what's going on.

**Comment by ehelms** [comment]
@wbclark Could you attach a Redmine issue?

**Comment by evgeni** [comment]
> If you haven't upgraded mongodb storage engine by now... oh well.

But, have we forced users to do so? There is nothing in the release notes of Katello (or Satellite, for that matter).

**Comment by ekohl** [comment]
The next version of Katello will be 4.0 and drop Pulp 2 which removes the need for MongoDB.

**Review by ekohl — APPROVED** [review]
I don't think we should be cleaning up custom-hiera.yaml since this doesn't remove MongoDB.

**Comment by evgeni** [comment]
Right, if that's 4.0+ only, then yeah.

**Pull request merged**
