### PR TITLE
Fixes #16932 - Provide default postgresql tuning

### PR DESCRIPTION
**Pull request by ekohl**
As of yet this is untested but I wanted a place to link to.

### CODE REVIEW

**Comment by psuriset** [comment]
Thanks for fixing this in foreman. These values seem to be good.

**Review by chris1984 — APPROVED** [review]

**Comment by ekohl** [comment]
Confirmed this works for me on nightly.

**Comment by mmoll** [comment]
This doesn't work with e.g. PostgreSQL 9.6:
```
LOG:  unrecognized configuration parameter "checkpoint_segments" in file "/etc/postgresql/9.6/main/postgresql.conf" line 629
FATAL:  configuration file "/etc/postgresql/9.6/main/postgresql.conf" contains errors
```
This exposes the same problem we had when trying to tune the Jenkins slaves. While RHEL 7.x always brings 9.2, recent Debian/Ubuntus bring 9.5, 9.6 or even 10. Also, there's the possibility to use postgresql.org repos with custom-hiera.yml to use recent PostgreSQLs with older OSes...

**Comment by ekohl** [comment]
Interesting. I can put the merging config in common, set everything that is shared here and set segments in OS-specific configs or leave it out.

**Comment by mmoll** [comment]
I just tested it with 9.6 and without `checkpoint_segments` but keeping the other settings it seems to work.

**Comment by ekohl** [comment]
Updated to not set `checkpoint_segments`.

**Comment by mmoll** [comment]
merged, bedankt @ekohl!

**Pull request merged**
