### PR TITLE
Rename foreman_proxy::puppetrun* to puppet

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by ekohl** [comment]
`.delete()` returns the previous value so it's like `pop()`?

**Comment by domcleal** [comment]
Yep: http://ruby-doc.org/core-1.8.7/Hash.html#method-i-delete

**Comment by ekohl** [comment]
:+1:

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Pull request merged**
