### PR TITLE
 Refs #37803 - Remove ProxyCommand option from Ansible options

### PR DESCRIPTION
**Pull request by adamlazik1**
Relates to https://github.com/theforeman/puppet-foreman_proxy/pull/845

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
@adamruzicka it looks good to me, but I'd appreciate your approval too.

**Review by ekohl — CHANGES_REQUESTED** [review]
Oh, please make the commit message `Refs #37803` so they're properly related in Redmine.

**Review by adamruzicka — APPROVED** [review]
LGTM, pending commit message change

**Comment by adamlazik1** [comment]
Thank you @ekohl and @adamruzicka. Changed the commit message.

**Comment by ekohl** [comment]
Thanks! I took the liberty to refine it a bit further.

**Pull request merged**
