### PR TITLE
Update submodules for 1.1-1 release

### PR DESCRIPTION
**Pull request by skottler**

### CODE REVIEW

**Comment by domcleal** [comment]
Lots of merge commits here?

**Comment by skottler** [comment]
Yeah sorry, fixing that right now.

**Comment by skottler** [comment]
Fixed it up @domcleal :+1:

**Comment by domcleal** [comment]
:+1: merge it!  Maybe merge develop into master too?

**Comment by skottler** [comment]
Yep that's what I've been doing to cut tags.

**Pull request merged**
