### PR TITLE
Refs #22513 - use appropriate puppetlabs/postgresql release

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
See a630083

**Review by ekohl — APPROVED** [review]
This should also go into 1.18.

**Comment by mmoll** [comment]
AFAICT there's something going on with the 5.5.0 vs. 5.6.0 release, so waiting...

**Comment by ekohl** [comment]
Restarted the build because https://forge.puppet.com/puppetlabs/postgresql is now 5.6.0.

**Comment by mmoll** [comment]
:green_heart: now

**Comment by ekohl** [comment]
Thanks!

**Pull request merged**
