### PR TITLE
Fixes #30193 - execute rpm commands outside the SCL

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Should we first kick off a nightly pipeline before we merge this?

**Comment by evgeni** [comment]
https://ci.theforeman.org/job/foreman-nightly-rpm-pipeline/651/ is running

**Comment by evgeni** [comment]
Might be worth waiting on https://github.com/theforeman/foreman-installer/pull/528 too :)

**Comment by evgeni** [comment]
also picked #528

**Comment by evgeni** [comment]
nightlies with all these changes passed, so I'm going to merge this now.

**Comment by evgeni** [comment]
of course only on el, and I didn't check debian

me--

https://github.com/theforeman/foreman-installer/pull/529

**Pull request merged**
