### PR TITLE
Fix REX Cockpit port and Azure support

### PR DESCRIPTION
**Pull request by ekohl**
theforeman-foreman 13.1.0 brings AzureRM and Azure CLI support. Also a bugfix in the Cockport port.

Depends on https://github.com/theforeman/puppet-foreman/pull/775.

### CODE REVIEW

**Comment by ekohl** [comment]
cc @tbrisker

**Review by evgeni — APPROVED** [review]
while I am unsure why this PR is called "fix" while it contains features, these are all features we want in 1.24, so ACK

**Review by tbrisker — APPROVED** [review]
Thanks @ekohl !

**Comment by ekohl** [comment]
> while I am unsure why this PR is called "fix" while it contains features, these are all features we want in 1.24, so ACK

Next time I'll write "Azure support and fix REX Cockpit port"

**Pull request merged**
