### PR TITLE
    Bump TargetRubyVersion to 2.7

### PR DESCRIPTION
**Pull request by archanaserver**
Raise RuboCop Ruby level from 2.5 to 2.7 in .rubocop.yml.

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Please use an accurate description of the commit. This does not add Ruby compatibility, but it raises the RuboCop Ruby level to 2.7.

**Comment by archanaserver** [comment]
> Please use an accurate description of the commit. This does not add Ruby compatibility, but it raises the RuboCop Ruby level to 2.7.

Sure @ekohl! Also this change can be pushed in here #883?

**Comment by ekohl** [comment]
> Sure @ekohl! Also this change can be pushed in here #883?

Yes, I think it can.

**Comment by archanaserver** [comment]
closing this one, cherry-picked here https://github.com/theforeman/foreman-installer/pull/883

**Pull request closed without merging**
