### PR TITLE
Fixes #37296 - Drop foreman-hooks

### PR DESCRIPTION
**Pull request by adamruzicka**

### CODE REVIEW

**Comment by evgeni** [comment]
I think this needs migrations like https://github.com/theforeman/foreman-installer/pull/927

**Comment by alexjfisher** [comment]
Is the plugin broken these days?  I've not used it recently, but use to quite a bit in the past.

**Comment by adamruzicka** [comment]
Not exactly broken, but unmaintained. It was superseded by foreman_webhooks, which should now be the way to go

**Comment by alexjfisher** [comment]
I hadn't seen this.  Just watched https://www.youtube.com/watch?v=sTld0H_PevA though :)

**Review by ehelms — APPROVED** [review]

**Pull request merged**
