### PR TITLE
Fixes #27884 - No hooks after packages are locked

### PR DESCRIPTION
**Pull request by mbacovsky**
Hooks may want to install packages prevented by version locking. Suggest with the "99' that locking should be last hook in the 'post' group

### CODE REVIEW

**Comment by mbacovsky** [comment]
@chris1984, could you please confirm this move is safe?

**Comment by chris1984** [comment]
@mbacovsky it looks safe, I am assuming you want it to run as the very last step?

**Review by ekohl — APPROVED** [review]

**Comment by ekohl** [comment]
LGTM, but will let @chris1984 and @mbacovsky agree before merging.

**Comment by mbacovsky** [comment]
@chris1984 correct, we need to lock packages as a last step so it does not prevent other steps (e.g mongo-syspath) from installing things.

**Review by chris1984 — APPROVED** [review]
Makes sense, ACK from Me. @ekohl if you can merge please.

**Pull request merged**
