### PR TITLE
fixes #30569 - Added migration to change logging pattern

### PR DESCRIPTION
**Pull request by domitea**
Complementary PR for https://github.com/theforeman/puppet-foreman/pull/847

This PR contains migration for changing logging layout

Thanks @ekohl for mention this!

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
Please copy the migration to `config/katello.migrations`. Note it uses a slightly different naming convention, but `bin/create-migration` can deal with that.

**Comment by ekohl** [comment]
Nit: please use `Add` instead of `Added`. https://chris.beams.io/posts/git-commit/ explains why using the imperative mood is a good thing.

**Comment by ekohl** [comment]
It's also better to reuse the Redmine issue because only together do they fix the issue. So here you'd use `Refs #29938`.

**Comment by domitea** [comment]
@ekohl migration to Katello added and commit message reworded. Thanks for the link!

**Comment by ehelms** [comment]
Close and re-opening to re-trigger tests

**Review by ehelms — APPROVED** [review]

**Pull request merged**
