### PR TITLE
Disable foreman_bootdisk by default

### PR DESCRIPTION
**Pull request by domcleal**
I don't think this was a good idea, so would like to remove it again from the default install so it's in the same boat as other plugins.

### CODE REVIEW

**Comment by ekohl** [comment]
Not against it, but what made you think it's not a good idea? Too many issues?

**Comment by domcleal** [comment]
No, not really, it's been pretty much stable.  I think I was anticipating it moving into core sooner than it is (that is, I have no plan to do the work any time soon) and don't feel that it's any more special than other plugins.

I'm also on a bit of a drive to minimise the default installation as every rubygem slows down boot times.

**Comment by ekohl** [comment]
Fair enough :+1:

**Comment by mmoll** [comment]
merged as 0a4ba0c :boot: :floppy_disk: , thanks @domcleal

**Pull request closed without merging**
