### PR TITLE
Refs #30251 - load a branding file if it's present

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by wbclark — APPROVED** [review]
I read over https://projects.theforeman.org/issues/30251 and https://github.com/theforeman/foreman-installer/pull/534 to get a sense of what this should accomplish and it looks good to me.

I suppose the branding file would be delivered in downstream packaging.

**Comment by evgeni** [comment]
> I suppose the branding file would be delivered in downstream packaging.

Correct, that's the idea.

Quick ping to @ehelms if he's OK with the file path I've picked?

**Review by ehelms — APPROVED** [review]

**Comment by ehelms** [comment]
[test foreman-installer]

**Comment by ehelms** [comment]
There is a valid Travis run passing.

**Pull request merged**
