### PR TITLE
Kafo > 0.0.12 allows to specify custom log filename

### PR DESCRIPTION
**Pull request by ares**
So let's discuss log filename.

The project is called `foreman-installer`, the script is named according to action `foreman-install`, later we may add other scripts like `foreman-check` or whatever 

I prefer having log files in `/var/log/$project_name/$script_name` in this case `/var/log/foreman-installer/foreman-install.log`

Also note that this won't have any effect until Kafo 0.0.13 is released.

### CODE REVIEW

**Comment by GregSutcliffe** [comment]
:+1:

**Comment by ares** [comment]
@domcleal @lzap you wanted to discuss this?

**Comment by domcleal** [comment]
Fine by me.  I kind of prefer foreman-installer to foreman-install for the name of the script + log, but it's fine as-is.

**Comment by lzap** [comment]
Hmmmm...

**Comment by domcleal** [comment]
@lzap insightful!

**Comment by ekohl** [comment]
Why the rename of the script to foreman-install anyway? Isn't it currently foreman-installer? I feel foreman-installer is a better name since foreman-install can (AFAIK) just write the config and not install. That's something I expect of an installer, but not an install command. This may just be bike shedding and since I don't use the installer, feel free to ignore it :)

**Comment by lzap** [comment]
My only opinion about that is it should be one command, one package name, one repo name. History shows we mis-type and cannot remember this. At least I am life-sentenced to make these mistakes. I don't care if this is foreman-install, installer or whatever.

**Comment by ares** [comment]
I renamed script to foreman-installer and changed the log filename accordingly. Please update your bookmarks if accepted :-)

**Comment by ekohl** [comment]
:+1: on changing to foreman-installer.

**Comment by domcleal** [comment]
:+1:

**Pull request merged**
