### PR TITLE
Submodule bump for theforeman modules

### PR DESCRIPTION
**Pull request by GregSutcliffe**
Not bumped external modules, they need testing. Can add if required.

### CODE REVIEW

**Comment by ekohl** [comment]
:+1: I'm bumping submodules in my production env and they all seem to work fine (including external)

**Comment by lzap** [comment]
Oh cool thanks for this.

Can you add also external ones? I'd love to test them all at once tomorrow :-)

**Comment by GregSutcliffe** [comment]
@lzap done

**Comment by lzap** [comment]
Going to test :-)

## 

Later,

 Lukas "lzap" Zapletal
 irc: lzap #theforeman

**Comment by lzap** [comment]
Got one minor issue:

```
[root@lzap-bb foreman-installer]# foreman-install --foreman-repo nightly --foreman-proxy-repo nightly -v
Unable to continue because of:
undocumented parameters in foreman_proxy: registered_name
```

Will issue PR to fix that.

**Comment by lzap** [comment]
Unfortunately:

```
[ INFO 2013-09-10 10:35:46 puppet] Syntax error at ')' at /usr/share/foreman-installer/modules/xinetd/manifests/service.pp:82 on node lzap-bb.brq.redhat.com
```

I fixed that upstream already, still waiting :-( https://github.com/puppetlabs/puppetlabs-xinetd/pull/20

But then:

```
[ INFO 2013-09-10 10:36:59 puppet] Could not find template 'foreman/foreman-report_.rb.erb' at /usr/share/foreman-installer/modules/foreman/manifests/puppetmaster.pp:36 on node lzap-bb.brq.redhat.com
```

The $report-api variable is empty for some reason. This is RHEL6 with puppet from EPEL6 - puppet-2.6.18-3.el6.noarch

**Comment by lzap** [comment]
It looks like all RHEL6 issues are sovled now, except the puppet 2.6 parsing of default values. I will retest once @ares come up with a solution. Thanks!

**Comment by lzap** [comment]
After those updates and fixes and @ares patch https://github.com/theforeman/kafo/pull/7 it looks there is one issue:

```
[ INFO 2013-09-11 03:28:19 puppet] Syntax error at ')' at /usr/share/foreman-installer/modules/postgresql/manifests/config/beforeservice.pp:51 on node hp-bl280cg6-01.rhts.eng.bos.redhat.com
```

Fixed here: https://github.com/puppetlabs/puppetlabs-postgresql/pull/239 that means if this is not closed today, we need to re-bump the pgsql version to the commit before this patch :-(

Except that - _go_ on RHEL6!

**Comment by GregSutcliffe** [comment]
Dropped psql bump, all others should be consistent

**Comment by lzap** [comment]
+1 Please merge.

**Pull request merged**
