### PR TITLE
Foreman 2.3.2 cherry picks

### PR DESCRIPTION
**Pull request by ekohl**
Draft PR since this includes a module updates which haven't been released yet:
* <del>https://github.com/theforeman/puppet-foreman_proxy_content/pull/313</del>
* https://github.com/theforeman/puppet-foreman_proxy_content/pull/314
* <del>https://github.com/theforeman/puppet-katello/pull/375</del>

### CODE REVIEW

**Comment by ekohl** [comment]
@evgeni reported the legacy dir migration broke nightly @ https://github.com/theforeman/foreman-installer/pull/634#issuecomment-760021781 but I think that picking it here to 2.3 will actually fix nightly upgrades again.

**Comment by evgeni** [comment]
my concerns were adressed in a recent discussion as follows:
* picking it will fix good 3.17 to 3.18 upgrades
* users on 3.18 already are in a weird state and will get manual help

**Comment by tbrisker** [comment]
[test foreman-installer]

**Comment by tbrisker** [comment]
[test installer] is it?

**Comment by evgeni** [comment]
the config says its
[test foreman-installer]

**Comment by tbrisker** [comment]
I guess it just doesn't like me because my first comment didn't trigger it...

**Review by tbrisker — APPROVED** [review]
Thanks @ekohl !

**Pull request merged**
